<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WoodCNC.Core\WoodCNC.Core.csproj" />
    <ProjectReference Include="..\..\src\WoodCNC.Contour\WoodCNC.Contour.csproj" />
  </ItemGroup>
</Project>
